title: Other
nav:
  - index.md
  - EKGF main site: https://ekgf.org
  - Principles: https://principles.ekgf.org
  - Maturity Model: https://maturity.ekgf.org
  - Method: https://method.ekgf.org
  - Component Catalog: https://catalog.ekgf.org
  - ...

